// Mocks generated by Mockito 5.4.4 from annotations
// in gamified_tax_deduction/test/core/services/achievement_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gamified_tax_deduction/core/models/achievement.dart' as _i4;
import 'package:gamified_tax_deduction/core/models/data_models.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i2.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i3.Future<_i2.Database>.value(_FakeDatabase_0()),
      ) as _i3.Future<_i2.Database>);

  @override
  _i3.Future<int> insertReceipt(_i5.Receipt? receipt) => (super.noSuchMethod(
        Invocation.method(
          #insertReceipt,
          [receipt],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i5.Receipt>> getAllReceipts() => (super.noSuchMethod(
        Invocation.method(
          #getAllReceipts,
          [],
        ),
        returnValue: _i3.Future<List<_i5.Receipt>>.value(<_i5.Receipt>[]),
      ) as _i3.Future<List<_i5.Receipt>>);

  @override
  _i3.Future<double> getTotalPotentialSavings() => (super.noSuchMethod(
        Invocation.method(
          #getTotalPotentialSavings,
          [],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<int> getReceiptCount() => (super.noSuchMethod(
        Invocation.method(
          #getReceiptCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.Achievement>> getAchievements() => (super.noSuchMethod(
        Invocation.method(
          #getAchievements,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.Achievement>>.value(<_i4.Achievement>[]),
      ) as _i3.Future<List<_i4.Achievement>>);

  @override
  _i3.Future<void> updateAchievement(_i4.Achievement? achievement) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAchievement,
          [achievement],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}
